apiVersion: v1
kind: Service

metadata:
  name: {{ include "redis-fastapi.fullname" . }}-fastapi-service
  labels:
    {{- include "redis-fastapi.labels" . | nindent 4 }}

spec:

  type: {{ .Values.fastapi.service.type }}

  selector:
    app: fastapi

  ports:

  - port: {{ .Values.fastapi.service.port }}

    targetPort: 8000

    {{- if eq .Values.fastapi.service.type "NodePort" }}
    nodePort: {{ .Values.fastapi.service.nodePort }}
    {{- end }}
