apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-fastapi.fullname" . }}-redis
  labels:
    {{- include "redis-fastapi.labels" . | nindent 4 }}
    app: redis

spec:
  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis
        {{- include "redis-fastapi.labels" . | nindent 8 }}

    spec:
      containers:

      - name: redis

        image: redis:7

        ports:
        - containerPort: 6379
          name: redis

        command:
        - redis-server
        - --requirepass
        - "$(REDIS_PASSWORD)"

        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "redis-fastapi.fullname" . }}-secret
              key: REDIS_PASSWORD

        resources:

          requests:
            cpu: 100m
            memory: 128Mi

          limits:
            cpu: 500m
            memory: 512Mi


        livenessProbe:

          tcpSocket:
            port: redis

          initialDelaySeconds: 20

          periodSeconds: 10


        readinessProbe:

          tcpSocket:
            port: redis

          initialDelaySeconds: 5

          periodSeconds: 5


        volumeMounts:

        - name: redis-data
          mountPath: /data


      volumes:

      - name: redis-data

        persistentVolumeClaim:

          claimName: {{ include "redis-fastapi.fullname" . }}-pvc
