apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "redis-fastapi.fullname" . }}-redis

  labels:
    {{- include "redis-fastapi.labels" . | nindent 4 }}


spec:

  replicas: {{ .Values.redis.replicaCount }}

  selector:
    matchLabels:
      app: redis


  template:

    metadata:

      labels:

        app: redis

        {{- include "redis-fastapi.labels" . | nindent 8 }}


    spec:

      containers:

      - name: redis

        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"


        ports:

        - containerPort: 6379


        env:

        - name: REDIS_PASSWORD

          valueFrom:

            secretKeyRef:

              name: {{ include "redis-fastapi.fullname" . }}-secret

              key: REDIS_PASSWORD


        volumeMounts:

        - name: redis-data

          mountPath: /data


      volumes:

      - name: redis-data

        persistentVolumeClaim:

          claimName: {{ include "redis-fastapi.fullname" . }}-pvc
