apiVersion: v1
kind: Secret

metadata:

  name: {{ include "redis-fastapi.fullname" . }}-secret

  labels:

    {{- include "redis-fastapi.labels" . | nindent 4 }}


type: Opaque


stringData:

  REDIS_PASSWORD: "redispassword"
