fastapi:
  replicaCount: 1

  image:
    repository: ghcr.io/jenish2053/redis-fastapi
    tag: latest

  service:
    type: NodePort
    port: 8000
    nodePort: 30080

redis:
  replicaCount: 1

  image:
    repository: redis
    tag: "7"

  service:
    type: ClusterIP
    port: 6379

  persistence:
    enabled: true
    size: 1Gi

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"
